
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jun 25 18:34:55 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NOT_EQUAL_TO = 32;
  public static final int INCREMENT = 22;
  public static final int CONST = 5;
  public static final int CHAR = 10;
  public static final int EQUALS = 24;
  public static final int LPAREN = 15;
  public static final int GREATER = 33;
  public static final int SEMI = 6;
  public static final int LESS = 35;
  public static final int MINUS = 25;
  public static final int DECREMENT = 23;
  public static final int RPAREN = 16;
  public static final int AND = 38;
  public static final int OR = 37;
  public static final int BOOL = 11;
  public static final int COMMA = 7;
  public static final int DIV = 29;
  public static final int LESS_EQUAL = 36;
  public static final int NUM = 9;
  public static final int PLUS = 27;
  public static final int IF = 20;
  public static final int EOF = 0;
  public static final int EQUAL = 8;
  public static final int GREATER_EQUAL = 34;
  public static final int NEW = 26;
  public static final int error = 1;
  public static final int MUL = 28;
  public static final int MOD = 30;
  public static final int IDENT = 12;
  public static final int VOID = 17;
  public static final int EQUAL_TO = 31;
  public static final int LBRACE = 3;
  public static final int ELSE = 21;
  public static final int LSQUARE = 13;
  public static final int READ = 18;
  public static final int RSQUARE = 14;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int PRINT = 19;
}

